import = [
  "~/.config/alacritty/themes/themes/nord.toml"
]

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
decorations = "none"
dynamic_padding = false

[window.padding]
x = 3
y = 3

[scrolling]
history = 100000

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"
