import = [
  "~/.config/alacritty/themes/themes/nord.toml"
]

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina Italic"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"
