on:
  push:

jobs:
  setup:
    runs-on: [self-hosted]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Extract branch name
        shell: bash
        run: |
          sleep 500
